Repository pytoyoda/ha_toyota, pull requests merged in 2025-04, with the labels that each got.

#81 Intercept and redirect loguru logs
  custom_components/toyota/__init__.py
Labels: :bug: bug

#85 Update ruff settings
  .pre-commit-config.yaml
  custom_components/toyota/__init__.py
  custom_components/toyota/binary_sensor.py
  custom_components/toyota/config_flow.py
  custom_components/toyota/device_tracker.py
  custom_components/toyota/entity.py
  custom_components/toyota/sensor.py
  custom_components/toyota/utils.py
  pyproject.toml
Labels: :wrench: enhancement

#86 Update README.md
  README.md
Labels: :memo: documentation

#92 update codacy config
  .codacy.yaml
Labels: :wrench: enhancement

#94 Add unit tests for config_flow
  .github/workflows/testing.yml
  custom_components/toyota/__init__.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/test_config_flow.py
Labels: :wrench: enhancement
