Repository pytoyoda/ha_toyota, pull requests merged in 2025-03, with the labels that each got.

#3 Update names and used library to pytoyoda
  README.md
  custom_components/toyota/__init__.py
  custom_components/toyota/binary_sensor.py
  custom_components/toyota/config_flow.py
  custom_components/toyota/entity.py
  custom_components/toyota/manifest.json
  custom_components/toyota/sensor.py
  custom_components/toyota/utils.py
  poetry.lock
  pyproject.toml
Labels: :warning: breaking change

#7 Update dependencies and pre-commit config
  .github/workflows/linting.yml
  .pre-commit-config.yaml
  custom_components/toyota/__init__.py
  custom_components/toyota/binary_sensor.py
  custom_components/toyota/config_flow.py
  custom_components/toyota/device_tracker.py
  custom_components/toyota/entity.py
  custom_components/toyota/sensor.py
  custom_components/toyota/utils.py
  poetry.lock
  pyproject.toml
Labels: :game_die: dependencies

#14 Fix pre-commit code quality
  renovate.json
Labels: :game_die: dependencies

#16 add bot label
  renovate.json
Labels: :wrench: enhancement

#24 Enable lockfileMaintenance
  poetry.lock
  pyproject.bak.toml
  renovate.json
Labels: :game_die: dependencies

#26 Use autofix for trivial lining errors
  .github/workflows/autofix.yml
Labels: :wrench: enhancement

#27 Use pre-commit ci instead of autofix
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  poetry.lock
  pyproject.toml
Labels: :wrench: enhancement

#35 Migrate to `pytoyoda` v3
  .github/workflows/pre-commit.yml
  custom_components/toyota/__init__.py
  custom_components/toyota/manifest.json
  poetry.lock
  pyproject.toml
Labels: :game_die: dependencies, :wrench: enhancement

#45 Fix non valid percentage values for battery and impove capability handling for sensors
  custom_components/toyota/const.py
  custom_components/toyota/sensor.py
Labels: :bug: bug, :wrench: enhancement

#47 Update german translations
  custom_components/toyota/translations/de.json
Labels: :speech_balloon: translation

#50 Hide fuel and total range sensors for electric vehicles
  custom_components/toyota/manifest.json
  custom_components/toyota/sensor.py
  pyproject.toml
Labels: :wrench: enhancement

#51 fix italian translation for passengerseat_window
  custom_components/toyota/translations/it.json
Labels: :bug: bug, :speech_balloon: translation

#52 Adjust TypeHints and error handling
  .pre-commit-config.yaml
  custom_components/toyota/__init__.py
  custom_components/toyota/binary_sensor.py
  custom_components/toyota/config_flow.py
  custom_components/toyota/device_tracker.py
  custom_components/toyota/entity.py
  custom_components/toyota/sensor.py
  custom_components/toyota/utils.py
Labels: :wrench: enhancement

#56 Fix blocking call during login
  custom_components/toyota/__init__.py
Labels: :bug: bug
